var	devices = new Array();

var cntdevice = 0;

devices[cntdevice] = new Object();
devices[cntdevice]["shortname"] = "2XH250";
devices[cntdevice]["ordernumber"] = "580221";
devices[cntdevice]["fullname"] = new Object();
devices[cntdevice]["fullname"]["de"] = "Leistungsverstärker 2XH250W/100V";
devices[cntdevice]["fullname"]["en"] = "Power Amplifier 2XH250W/100V";
devices[cntdevice]["fullname"]["kr"] = "앰프 2XH250W/100V (KC 미인증)";
devices[cntdevice]["standbycurrent"] = 1.6;
devices[cntdevice]["18current"] = 8.7;
devices[cntdevice]["13current"] = 21.3;
devices[cntdevice]["11current"] = 38.8;
devices[cntdevice]["offcurrent"] = 0.0;
devices[cntdevice]["weight"] = 17;
devices[cntdevice]["rackunits"] = 2;
devices[cntdevice]["backupdevice"] = true;
devices[cntdevice]["totaloffcurrent"] = 0;
cntdevice++;

devices[cntdevice] = new Object();
devices[cntdevice]["shortname"] = "2XH500";
devices[cntdevice]["ordernumber"] = "580222";
devices[cntdevice]["fullname"] = new Object();
devices[cntdevice]["fullname"]["de"] = "Leistungsverstärker 2XH500W/100V";
devices[cntdevice]["fullname"]["en"] = "Power Amplifier 2XH500W/100V";
devices[cntdevice]["fullname"]["kr"] = "앰프 2XH500W/100V (KC 미인증)";
devices[cntdevice]["standbycurrent"] = 2;
devices[cntdevice]["18current"] = 19.3;
devices[cntdevice]["13current"] = 40;
devices[cntdevice]["11current"] = 86;
devices[cntdevice]["offcurrent"] = 0.0;
devices[cntdevice]["weight"] = 21;
devices[cntdevice]["rackunits"] = 2;
devices[cntdevice]["backupdevice"] = true;
devices[cntdevice]["totaloffcurrent"] = 0;
cntdevice++;

devices[cntdevice] = new Object();
devices[cntdevice]["shortname"] = "2XD250";
devices[cntdevice]["ordernumber"] = "580231";
devices[cntdevice]["fullname"] = new Object();
devices[cntdevice]["fullname"]["de"] = "Leistungsverstärker 2XD250W/100V";
devices[cntdevice]["fullname"]["en"] = "Power Amplifier 2XD250W/100V";
devices[cntdevice]["fullname"]["kr"] = "앰프 2XD250W/100V";
devices[cntdevice]["standbycurrent"] = 0.4;
devices[cntdevice]["18current"] = 3.6;
devices[cntdevice]["13current"] = 8.8;
devices[cntdevice]["11current"] = 25;
devices[cntdevice]["offcurrent"] = 0.1;
devices[cntdevice]["weight"] = 16.5;
devices[cntdevice]["rackunits"] = 2;
devices[cntdevice]["backupdevice"] = true;
devices[cntdevice]["totaloffcurrent"] = 0;
cntdevice++;

devices[cntdevice] = new Object();
devices[cntdevice]["shortname"] = "2XD400";
devices[cntdevice]["ordernumber"] = "580232";
devices[cntdevice]["fullname"] = new Object();
devices[cntdevice]["fullname"]["de"] = "Leistungsverstärker 2XD400W/100V";
devices[cntdevice]["fullname"]["en"] = "Power Amplifier 2XD400W/100V";
devices[cntdevice]["fullname"]["kr"] = "앰프 2XD400W/100V";
devices[cntdevice]["standbycurrent"] = 0.5;
devices[cntdevice]["18current"] = 5.6;
devices[cntdevice]["13current"] = 13.9;
devices[cntdevice]["11current"] = 40.5;
devices[cntdevice]["offcurrent"] = 0.1;
devices[cntdevice]["weight"] = 19;
devices[cntdevice]["rackunits"] = 2;
devices[cntdevice]["backupdevice"] = true;
devices[cntdevice]["totaloffcurrent"] = 0;
cntdevice++;

devices[cntdevice] = new Object();
devices[cntdevice]["shortname"] = "DOM4-8";
devices[cntdevice]["ordernumber"] = "583361.22";
devices[cntdevice]["fullname"] = new Object();
devices[cntdevice]["fullname"]["de"] = "Digitales Output-Modul DOM4-8";
devices[cntdevice]["fullname"]["en"] = "Digital Output Module DOM4-8";
devices[cntdevice]["fullname"]["kr"] = "디지털 출력 모듈 DOM4-8";
devices[cntdevice]["standbycurrent"] = 1.0;
devices[cntdevice]["18current"] = 1.6;
devices[cntdevice]["13current"] = 1.6;
devices[cntdevice]["11current"] = 1.6;
devices[cntdevice]["offcurrent"] = 1.0;
devices[cntdevice]["weight"] = 5.3;
devices[cntdevice]["rackunits"] = 1;
devices[cntdevice]["backupdevice"] = false;
devices[cntdevice]["totaloffcurrent"] = 0;
cntdevice++;

devices[cntdevice] = new Object();
devices[cntdevice]["shortname"] = "DOM4-24";
devices[cntdevice]["ordernumber"] = "583362.22";
devices[cntdevice]["fullname"] = new Object();
devices[cntdevice]["fullname"]["de"] = "Digitales Output-Modul DOM4-24";
devices[cntdevice]["fullname"]["en"] = "Digital Output Module DOM4-24";
devices[cntdevice]["fullname"]["kr"] = "디지털 출력 모듈 DOM4-24";
devices[cntdevice]["standbycurrent"] = 1.0;
devices[cntdevice]["18current"] = 1.8;
devices[cntdevice]["13current"] = 1.8;
devices[cntdevice]["11current"] = 1.8;
devices[cntdevice]["offcurrent"] = 1.0;
devices[cntdevice]["weight"] = 5.7;
devices[cntdevice]["rackunits"] = 1;
devices[cntdevice]["backupdevice"] = false;
devices[cntdevice]["totaloffcurrent"] = 0;
cntdevice++;

devices[cntdevice] = new Object();
devices[cntdevice]["shortname"] = "SCU";
devices[cntdevice]["ordernumber"] = "583381.22";
devices[cntdevice]["fullname"] = new Object();
devices[cntdevice]["fullname"]["de"] = "System-Kommunikationseinheit SCU";
devices[cntdevice]["fullname"]["en"] = "System Communication Unit SCU";
devices[cntdevice]["fullname"]["kr"] = "시스템 통신 유닛 SCU";
devices[cntdevice]["standbycurrent"] = 1.0;
devices[cntdevice]["18current"] = 1.2;
devices[cntdevice]["13current"] = 1.2;
devices[cntdevice]["11current"] = 1.2;
devices[cntdevice]["offcurrent"] = 1.0;
devices[cntdevice]["weight"] =4;
devices[cntdevice]["rackunits"] = 1;
devices[cntdevice]["backupdevice"] = false;
devices[cntdevice]["totaloffcurrent"] = 0;
cntdevice++;

devices[cntdevice] = new Object();
devices[cntdevice]["shortname"] = "Switch";
devices[cntdevice]["ordernumber"] = "583392 / 93";
devices[cntdevice]["fullname"] = new Object();
devices[cntdevice]["fullname"]["de"] = "LWL Ethernetswitch (Multi-/Singlemode)";
devices[cntdevice]["fullname"]["en"] = "Fiber Optic Ethernet Switch (Multi-/Singlemode)";
devices[cntdevice]["fullname"]["kr"] = "광 케이블 이더넷 스위치 (멀티/싱글 모드)";
devices[cntdevice]["standbycurrent"] = 0.25;
devices[cntdevice]["18current"] = 0.25;
devices[cntdevice]["13current"] = 0.25;
devices[cntdevice]["11current"] = 0.25;
devices[cntdevice]["offcurrent"] = 0.25;
devices[cntdevice]["weight"] = 0;
devices[cntdevice]["rackunits"] = 0;
devices[cntdevice]["backupdevice"] = false;
devices[cntdevice]["totaloffcurrent"] = 0;
cntdevice++;